Calculadora de salario
Leonardosu/Projeto-TDD pull request #1
Opened 2023-04-12 22:47 UTC by Leonardosu

2023-04-12 23:43 UTC, lucasbrenner requested changes

2023-04-12 23:43 UTC, lucasbrenner commented on Calculadora-de-Salario/src/model/Funcionario.java
> +    public Funcionario(String nome, String email, double salario, Cargo cargo) {
Criar código e teste para verificar se a entrada está válida.

2023-04-12 23:43 UTC, lucasbrenner commented on Calculadora-de-Salario/test/CalculadoraTest.java
> +    private Funcionario getFuncinario(Cargo cargo, double salario) {
O nome deveria ser `getFuncionario`

2023-04-12 23:43 UTC, lucasbrenner commented on Calculadora-de-Salario/src/model/Funcionario.java
> +        this.salario = salario;
Checar se salário é maior ou igual a zero.

2023-04-12 23:43 UTC, lucasbrenner commented on Calculadora-de-Salario/src/Calculadora.java
> +        }
Adicionar caso default.

2023-04-12 23:43 UTC, lucasbrenner commented on Calculadora-de-Salario/src/Calculadora.java
> +        return salario * (100 - desconto);
`getDesconto` deveria retornar um valor entre 0 e 1, e o salário deve ser multiplicado por `1 - desconto`.

2023-04-13 00:13 UTC, Leonardosu commented on Calculadora-de-Salario/src/model/Funcionario.java
> +    public Funcionario(String nome, String email, double salario, Cargo cargo) {
Feito.

2023-04-13 00:13 UTC, Leonardosu commented on Calculadora-de-Salario/test/CalculadoraTest.java
> +    private Funcionario getFuncinario(Cargo cargo, double salario) {
Feito.

2023-04-13 00:14 UTC, Leonardosu commented on Calculadora-de-Salario/src/model/Funcionario.java
> +        this.salario = salario;
Feito.

2023-04-13 00:14 UTC, Leonardosu commented on Calculadora-de-Salario/src/Calculadora.java
> +        }
Feito.

2023-04-13 00:14 UTC, Leonardosu commented on Calculadora-de-Salario/src/Calculadora.java
> +        return salario * (100 - desconto);
Corrigido.

2023-04-13 00:14 UTC, merged